### PR TITLE
fix: render `bodyPrepend` in template

### LINKED ISSUE #722: Missing BODY_PREPEND placeholder in app template
In the [renderer](https://github.com/nuxt/bridge/blob/b4b2daca16ff531edf65e4c5db150477d1bf6637/packages/bridge/src/runtime/nitro/renderer.ts#L235), the `htmlContext.bodyPreprend` array is assigned to the `BODY_PREPEND` property placeholder in the app template (`.nuxt/views/document.template.mjs`) but the template (and `.nuxt/views/app.template.html` as well), does not contain that placeholder.

I can submit a PR to fix this issue, but I'd like to know what's your opinion on the best solution:

1. add the `BODY_PREPEND` to the app template (not sure where it is stored)
2. prepend the contents to APP like we already do for the `bodyAppend` property:
```diff
- BODY_PREPEND: joinTags(htmlContext.bodyPreprend),
- APP: _rendered.html + joinTags(htmlContext.bodyAppend)
+ APP: joinTags(htmlContext.bodyPreprend) + _rendered.html + joinTags(htmlContext.bodyAppend)
```

### PR DESCRIPTION
**Pull request by dwightjack**
These changes apply to `packages/bridge/src/runtime/nitro/renderer.ts`:

- Fix a typo in the `NuxtRenderHTMLContext` object where `bodyPreprend` should be `bodyPrepend` (this is a breaking change, I guess)
- Render the content of the `bodyPrepend` in the template

### 🔗 Linked issue

- https://github.com/nuxt/bridge/issues/722

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [x] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Resolves #722

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: packages/bridge/src/runtime/nitro/renderer.ts [hunk 1]
```diff
@@ -234,8 +234,8 @@ export default defineRenderHandler(async (event) => {
         HEAD_ATTRS: joinAttrs(htmlContext.headAttrs),
         HEAD: joinTags(htmlContext.head),
         BODY_ATTRS: joinAttrs(htmlContext.bodyAttrs),
-        BODY_PREPEND: joinTags(htmlContext.bodyPreprend),
-        APP: _rendered.html + joinTags(htmlContext.bodyAppend)
+        BODY_PREPEND: joinTags(htmlContext.bodyPrepend),
+        APP: joinTags(htmlContext.bodyPrepend) + _rendered.html + joinTags(htmlContext.bodyAppend)
```
Comment (danielroe) [inline packages/bridge/src/runtime/nitro/renderer.ts:238]: Is there a reason that `bodyPrepend` is included twice?

Comment (dwightjack) [reply packages/bridge/src/runtime/nitro/renderer.ts]: You are right, sorry. The `BODY_PREPEND` placeholder doesn't exist in the template so I removed it (https://github.com/nuxt/bridge/pull/837/commits/9fd7ad6c08a14c9115faa781d6d0ff2921e5fae7).

**Review by danielroe — APPROVED** [review]

**Review by danielroe — APPROVED** [review]

**Comment by danielroe** [comment]
Thank you ❤️
